### PR TITLE
Fix #17 ensure to call Close()

### LINKED ISSUE #17: Failed to close WriteCloser
https://github.com/reproio/columnify/blob/21bb8711710f43e7313e2f68520ba37740bbfb25/cmd/columnify/columnify.go#L37-L46

`log.Fatalf` calls `os.Exit(1)`, which terminates immediately program without calling `defer` functions. So, when `WriteFromFiles()` is failed, `WriteCloser` will not be closed.

### PR DESCRIPTION
**Pull request by syucream**
https://github.com/reproio/columnify/issues/17

### CODE REVIEW

File: cmd/columnify/columnify.go [hunk 1]
```diff
@@ -18,6 +18,16 @@ func printUsage() {
 	flag.PrintDefaults()
 }
 
+func columnify(c columnifier.Columnifier, files []string) (err error) {
+	defer func() {
+		err = c.Close()
```
Comment (itchyny) [inline cmd/columnify/columnify.go:23]: This assignment overwrites the `err` value, even if `c.WriteFromFiles(files)` returns non-nil error. So the error from `c.WriteFromFiles(files)` is not reported anymore. The correct fix is, call `c.Close()`, but assign to `err` only when the value (returned by `c.WriteFromFiles(files)` is `nil`.

Comment (syucream) [reply cmd/columnify/columnify.go:23]: oops, thanks for your suggestion! I've just encountered this issue ... anyway I created an issue for that https://github.com/reproio/columnify/issues/49 and will fix it.
